### ISSUE TITLE
Powerpoint

### ISSUE THREAD

**Issue by pjilge** [Mogryxx/MEIN-Projekt#1]
[MEIN.pptx](https://github.com/Mogryxx/MEIN-Projekt/files/3145546/MEIN.pptx)

**Comment by Mogryxx** [comment]
[MEIN (1).pptx](https://github.com/Mogryxx/MEIN-Projekt/files/3145558/MEIN.1.pptx)

**Comment by AranethXIII** [comment]
https://drive.google.com/file/d/1zJSGm-lniAbVkgVdD_l5-pODnUem1Mqs/view Vorlage

**Comment by Mogryxx** [comment]
[MEIN Projekt.pptx](https://github.com/Mogryxx/MEIN-Projekt/files/3145577/MEIN.Projekt.pptx)
